/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAbout {
        "ngo": any;
    }
    interface AppHome {
        "ngo": any;
    }
    interface AppLegal {
        "ngo": any;
    }
    interface AppOne {
        "ngo": any;
        "project": number;
    }
    interface AppPress {
        "ngo": any;
    }
    interface AppProjects {
        "ngo": any;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLegalElement extends Components.AppLegal, HTMLStencilElement {
    }
    var HTMLAppLegalElement: {
        prototype: HTMLAppLegalElement;
        new (): HTMLAppLegalElement;
    };
    interface HTMLAppOneElement extends Components.AppOne, HTMLStencilElement {
    }
    var HTMLAppOneElement: {
        prototype: HTMLAppOneElement;
        new (): HTMLAppOneElement;
    };
    interface HTMLAppPressElement extends Components.AppPress, HTMLStencilElement {
    }
    var HTMLAppPressElement: {
        prototype: HTMLAppPressElement;
        new (): HTMLAppPressElement;
    };
    interface HTMLAppProjectsElement extends Components.AppProjects, HTMLStencilElement {
    }
    var HTMLAppProjectsElement: {
        prototype: HTMLAppProjectsElement;
        new (): HTMLAppProjectsElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-about": HTMLAppAboutElement;
        "app-home": HTMLAppHomeElement;
        "app-legal": HTMLAppLegalElement;
        "app-one": HTMLAppOneElement;
        "app-press": HTMLAppPressElement;
        "app-projects": HTMLAppProjectsElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppAbout {
        "ngo"?: any;
    }
    interface AppHome {
        "ngo"?: any;
    }
    interface AppLegal {
        "ngo"?: any;
    }
    interface AppOne {
        "ngo"?: any;
        "project"?: number;
    }
    interface AppPress {
        "ngo"?: any;
    }
    interface AppProjects {
        "ngo"?: any;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-about": AppAbout;
        "app-home": AppHome;
        "app-legal": AppLegal;
        "app-one": AppOne;
        "app-press": AppPress;
        "app-projects": AppProjects;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-legal": LocalJSX.AppLegal & JSXBase.HTMLAttributes<HTMLAppLegalElement>;
            "app-one": LocalJSX.AppOne & JSXBase.HTMLAttributes<HTMLAppOneElement>;
            "app-press": LocalJSX.AppPress & JSXBase.HTMLAttributes<HTMLAppPressElement>;
            "app-projects": LocalJSX.AppProjects & JSXBase.HTMLAttributes<HTMLAppProjectsElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
